CREATE TABLE IF NOT EXISTS company_size_multipliers (
    id INT AUTO_INCREMENT PRIMARY KEY,
    size_category VARCHAR(50) NOT NULL UNIQUE,
    multiplier DECIMAL(5,2) NOT NULL DEFAULT 1.00,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
